spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://www.luohuacanyue.top:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: zhaoqi
      password: qr3ew8[2;V
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      maxActive: 200
      minIdle: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000 
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      
security:
    basic:
      enabled: false    
      

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
 